apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {storageClassName}
  volumeMode: Filesystem
---

apiVersion: redis.kun/v1alpha1
kind: RedisClusterBackup
metadata:
  name: rediscluster-backup
  namespace: user-system-{{ .Values.bfl.username }}
  annotations:
    redis.kun/scope: cluster-scoped
spec:
  image: bytetrade/redis-backup-tools:redis-6.2.13
  # on same namespace
  redisClusterName: redis-cluster
  local:
    mountPath: /back
    hostPath:
      type: DirectoryOrCreate
      path: {{ .Values.userspace.dbdata }}/redisbackup
